version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - env_var_db_host=$(echo $DB_HOST)
      - env_var_db_username=$(echo $DB_USERNAME)
      - env_var_db_password=$(echo $DB_PASSWORD)
      - export DB_HOST=$env_var_db_host
      - export DB_USERNAME=$env_var_db_username
      - export DB_PASSWORD=$env_var_db_password
      - mvn -e clean install
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - target/*.jar
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes
